#!/bin/sh
case "$(file --dereference --brief --mime-type -- "$1")" in
    application/x-tar) tar tf "$1" ;;
    application/zip) unzip -l "$1" ;;
    application/octet-stream) xxd -R always "$1" ;;
    text/*|application/json|message/*|image/svg+xml) bat --terminal-width $(($4-2)) -f "$1" ;;
    *) exiftool "$1" ;;
esac
exit 1
